{
 "title": "Authelia Community Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(authelia_request,job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(authelia_request,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "description": "Actual memory usage of the authelia process",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "description": "Single core CPU usage",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(process_cpu_seconds_total{job=\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "stat",
   "description": "Inbound network traffic",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_network_receive_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "stat",
   "description": "Outbound network traffic",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_network_transmit_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Request Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Authelia Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(instance) (authelia_request{job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(authelia_request{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top slow requests",
   "type": "timeseries",
   "description": "The duration of some requests may be intentionally increased by Authelia's brute-force & enumeration prevention mechanisms. [Learn More](https://www.authelia.com/overview/security/measures/#protection-against-username-enumeration-and-password-brute-force-attacks)",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15, authelia_request_duration_sum{job=\"$job\",instance=~\"$instance\"} / authelia_request_duration_count{job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Http Code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(authelia_request{job=\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  { "title": "Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request duration",
   "type": "heatmap",
   "description": "The duration of some requests may be intentionally increased by Authelia's brute-force & enumeration prevention mechanisms. [Learn More](https://www.authelia.com/overview/security/measures/#protection-against-username-enumeration-and-password-brute-force-attacks)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(le) (rate(authelia_request_duration_bucket{job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "description": "The duration of some requests may be intentionally increased by Authelia's brute-force & enumeration prevention mechanisms. [Learn More](https://www.authelia.com/overview/security/measures/#protection-against-username-enumeration-and-password-brute-force-attacks)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(authelia_request_duration_bucket{job=\"$job\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(authelia_request_duration_bucket{job=\"$job\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  { "title": "Authentication Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "First factor method usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(authelia_authn{job=\"$job\", instance=~\"$instance\", banned=\"false\"})",
     "legendFormat": "password"
    },
    {
     "expr": "sum(authelia_authn_passkey{job=\"$job\", instance=~\"$instance\", success=\"true\"})",
     "legendFormat": "passkey"
    }
   ]
  },
  {
   "title": "Second factor method usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (authelia_authn_second_factor{job=\"$job\", instance=~\"$instance\", banned=\"false\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Authz requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(authelia_authz{job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Authn requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(authelia_authn{job=\"$job\", instance=~\"$instance\", success=\"true\", banned=\"false\"}[$__rate_interval]))",
     "legendFormat": "[password] successful"
    },
    {
     "expr": "sum(rate(authelia_authn{job=\"$job\", instance=~\"$instance\", success=\"false\", banned=\"false\"}[$__rate_interval]))",
     "legendFormat": "[password] failure"
    },
    {
     "expr": "sum(rate(authelia_authn{job=\"$job\", instance=~\"$instance\", success=\"false\", banned=\"true\"}[$__rate_interval]))",
     "legendFormat": "[password] banned"
    },
    {
     "expr": "sum(rate(authelia_authn_passkey{job=\"$job\", instance=~\"$instance\", success=\"true\"}[$__rate_interval]))",
     "legendFormat": "[passkey] successful"
    },
    {
     "expr": "sum(rate(authelia_authn_passkey{job=\"$job\", instance=~\"$instance\", success=\"false\"}[$__rate_interval]))",
     "legendFormat": "[passkey] failure"
    }
   ]
  },
  {
   "title": "Authn second factor requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(success, type) (rate(authelia_authn_second_factor{job=\"$job\", instance=~\"$instance\", banned=\"false\"}[$__rate_interval]))",
     "legendFormat": "[{{type}}] success: {{success}}"
    },
    {
     "expr": "sum by(banned, type) (rate(authelia_authn_second_factor{job=\"$job\",instance=~\"$instance\", banned=\"true\"}[$__rate_interval]))",
     "legendFormat": "[{{type}}] banned"
    }
   ]
  },
  { "title": "Authentication Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Authentication duration",
   "type": "heatmap",
   "description": "The duration of some requests may be intentionally increased by Authelia's brute-force & enumeration prevention mechanisms. [Learn More](https://www.authelia.com/overview/security/measures/#protection-against-username-enumeration-and-password-brute-force-attacks)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(le) (rate(authelia_authn_duration_bucket{job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication 90th percentile request duration",
   "type": "timeseries",
   "description": "The duration of some requests may be intentionally increased by Authelia's brute-force & enumeration prevention mechanisms. [Learn More](https://www.authelia.com/overview/security/measures/#protection-against-username-enumeration-and-password-brute-force-attacks)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, success) (rate(authelia_authn_duration_bucket{job=\"$job\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "Success: {{success}}"
    }
   ]
  },
  { "title": "OpenID Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "OIDC Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, code) (rate(authelia_request_duration_openid_connect_count{job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{method}}[{{code}}] on {{endpoint}}"
    }
   ]
  },
  {
   "title": "OIDC Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(le) (rate(authelia_request_duration_openid_connect_bucket{job=\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OIDC 90th percentile request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, code, endpoint) (rate(authelia_request_duration_openid_connect_bucket{job=\"$job\",instance=~\"$instance\"}[5m])))",
     "legendFormat": "{{method}}[{{code}}] on {{endpoint}}"
    }
   ]
  }
 ]
}